[mgr]
sort_by = "btime"
sort_reverse = true
sort_sensitive = false
sort_dir_first = true
linemode = "size"
mouse_events = []

[preview]
wrap = "yes"
tab_size = 2
image_filter = "lanczos3"
image_quality = 90

[tasks]
image_bound = [20000, 20000]

[plugin]
prepend_preloaders = [
  # Replace magick, image, video with mediainfo
  { mime = "{audio,video,image}/*", run = "mediainfo" },
  { mime = "application/subrip", run = "mediainfo" },
  # Adobe Illustrator, Adobe Photoshop is image/adobe.photoshop, already handled above
  { mime = "application/postscript", run = "mediainfo" },
]
prepend_previewers = [
  # Replace magick, image, video with mediainfo
  { mime = "{audio,video,image}/*", run = "mediainfo" },
  { mime = "application/subrip", run = "mediainfo" },
  # Adobe Illustrator, Adobe Photoshop is image/adobe.photoshop, already handled above
  { mime = "application/postscript", run = "mediainfo" },
]
# There are more extensions which are supported by mediainfo.
# Just add file's MIME type to `previewers`, `preloaders` above.
# https://mediaarea.net/en/MediaInfo/Support/Formats

[[plugin.prepend_fetchers]]
id = "mime"
url = "*"
run = "mime-ext"
prio = "high"
